services:
    phd_exceptional_validation:
        class: PhPhD\ExceptionalValidationBundle\Messenger\ExceptionalValidationMiddleware
        arguments:
            - '@phd_exceptional_validation.exception_handler'

    phd_exceptional_validation.exception_handler:
        class: PhPhD\ExceptionalValidation\Handler\DefaultExceptionHandler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler'
            - '@phd_exceptional_validation.violations_list_formatter'
        lazy: true
        tags:
            - { name: 'proxy', interface: 'PhPhD\ExceptionalValidation\Handler\ExceptionHandler' }

    phd_exceptional_validation.rule_set_assembler:
        alias: phd_exceptional_validation.rule_set_assembler.object

    phd_exceptional_validation.violations_list_formatter:
        class: PhPhD\ExceptionalValidation\Formatter\DefaultViolationListFormatter
        arguments:
            - '@phd_exceptional_validation.violation_formatter'
        lazy: true
        tags:
            - { name: 'proxy', interface: 'PhPhD\ExceptionalValidation\Formatter\ExceptionViolationListFormatter' }

    phd_exceptional_validation.violation_formatter:
        class: PhPhD\ExceptionalValidation\Formatter\DelegatingExceptionViolationFormatter
        arguments:
            - !tagged_locator { tag: 'exceptional_validation.violation_formatter', index_by: 'id' }

    phd_exceptional_validation.violation_formatter.default:
        class: PhPhD\ExceptionalValidation\Formatter\DefaultViolationFormatter
        arguments:
            - '@translator'
            - '%validator.translation_domain%'
        tags:
            - { name: 'exceptional_validation.violation_formatter', id: 'default' }

    phd_exceptional_validation.rule_set_assembler.object:
        class: PhPhD\ExceptionalValidation\Assembler\Object\ObjectRuleSetAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.object.rules'

    phd_exceptional_validation.rule_set_assembler.object.rules:
        class: PhPhD\ExceptionalValidation\Assembler\Object\Rules\ObjectRulesAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.property'

    phd_exceptional_validation.rule_set_assembler.property:
        class: PhPhD\ExceptionalValidation\Assembler\Object\Rules\Property\PropertyRuleSetAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.property.rules'

    phd_exceptional_validation.rule_set_assembler.property.rules:
        class: PhPhD\ExceptionalValidation\Assembler\CompositeRuleSetAssembler
        arguments:
            -   - '@phd_exceptional_validation.rule_set_assembler.property.rules.captures'
                - '@phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_object'
                - '@phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_iterable'

    phd_exceptional_validation.rule_set_assembler.property.rules.captures:
        class: PhPhD\ExceptionalValidation\Assembler\Object\Rules\Property\Rules\PropertyCaptureRulesAssembler

    phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_object:
        class: PhPhD\ExceptionalValidation\Assembler\Object\Rules\Property\Rules\PropertyNestedValidObjectRuleAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.object'
        lazy: true
        tags:
            - { name: 'proxy', interface: 'PhPhD\ExceptionalValidation\Assembler\CaptureRuleSetAssembler' }

    phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_iterable:
        class: PhPhD\ExceptionalValidation\Assembler\Object\Rules\Property\Rules\PropertyNestedValidIterableRulesAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.iterable_of_objects'
        lazy: true
        tags:
            - { name: 'proxy', interface: 'PhPhD\ExceptionalValidation\Assembler\CaptureRuleSetAssembler' }

    phd_exceptional_validation.rule_set_assembler.iterable_of_objects:
        class: PhPhD\ExceptionalValidation\Assembler\Object\IterableOfObjectsRuleSetAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.object'
